### PR TITLE
bullets and string translation fixes

### PR DESCRIPTION
**Pull request by rolandtoth**
- replace "&bull;" with "•"
- restrict translatable strings
- add translation context **FILE**
- replace "\n" with PHP_EOL

### CODE REVIEW

**Comment by adrianbj** [comment]
Thanks @rolandtoth - can you explain what adding **FILE** actually does - I have seen it in a few modules (even some of my early modules have it from copying from others), but I can't find much in the way of explanation of why it is needed when translating strings.

Thanks for the reminder on using PHP_EOL - I really need to get into the habit of using that!

**Comment by rolandtoth** [comment]
It adds a textdomain, so translatable strings will get "namespaced" and will not get mixed with other strings. See
https://processwire.com/api/multi-language-support/code-i18n/#using-textdomains
https://github.com/ryancramerdesign/ProcessWire/blob/master/wire/core/LanguageFunctions.php#L20

**Comment by adrianbj** [comment]
Thanks - I really should have just looked it up in the source code :)

**Comment by rolandtoth** [comment]
Thanks!

**Pull request merged**
